# Generated by Django 3.2.8 on 2021-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='nami_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
